// Generated by scripts/generate-app-registry.mjs. Do not edit directly.
import { BookOpen, ChartSpline, ShieldCheck } from 'lucide-react';
import type { ShellAppDefinition } from './types';

const loadOptionsStrategyLab = () => import('../apps/options-strategy-lab/OptionsStrategyLabApp');
const loadDiffusionTimeSliceLab = () => import('../apps/diffusion-time-slice-lab/DiffusionTimeSliceLabApp');
const loadAccessControl = () => import('../apps/access-control/AccessControlApp');

export const generatedAppRegistry: readonly ShellAppDefinition[] = [
  {
    key: "options-strategy-lab",
    version: "0.8.0",
    path: "/apps/options-strategy-lab",
    title: "選擇權策略分析",
    subtitle: "策略組合、Greeks 與損益曲線",
    description: "開發驗證階段預設僅平台管理員可進入；管理員仍可依發布階段調整為公開、所有會員或個別授權。",
    icon: ChartSpline,
    status: "enabled",
    displayMode: "responsive",
    keepAlive: true,
    load: loadOptionsStrategyLab,
    access: "identity",
    sourceActivation: {"displayName":"選擇權策略分析","category":"application","removable":true,"protected":false,"defaultAccessMode":"admins_only","allowedAccessModes":["public","all_members","grant_required","admins_only"],"entitlements":[{"key":"course","displayName":"課程進階功能","description":"登入會員獲管理員授權後，解鎖課程模板、Greeks 曲線與多曲線比較。"}],"adminAllowed":true},
  },
  {
    key: "diffusion-time-slice-lab",
    version: "0.1.0",
    path: "/apps/diffusion-time-slice-lab",
    title: "熱擴散到華爾街",
    subtitle: "機率分布、時間與波動率",
    description: "離線計算高斯機率密度，從正面、傾斜與俯視角觀察時間和波動率如何改變分布。",
    icon: BookOpen,
    status: "preview",
    displayMode: "standard",
    load: loadDiffusionTimeSliceLab,
    access: "identity",
    sourceActivation: {"displayName":"熱擴散到華爾街","category":"application","removable":true,"protected":false,"defaultAccessMode":"admins_only","allowedAccessModes":["public","all_members","grant_required","admins_only"],"entitlements":[],"adminAllowed":true},
  },
  {
    key: "access-control",
    version: "0.1.0",
    path: "/apps/access-control",
    title: "會員與權限",
    subtitle: "會員狀態、App 權限與安裝管理",
    description: "由平台管理員管理會員，以及各 App 對一般會員的開放方式。",
    icon: ShieldCheck,
    status: "preview",
    displayMode: "responsive",
    load: loadAccessControl,
    access: "identity",
  },
];
