// Generated by scripts/generate-app-registry.mjs. Do not edit directly.
import { Monitor, ShieldCheck, Smartphone } from 'lucide-react';
import type { ShellAppDefinition } from './types';

const loadDemo = () => import('../apps/demo/DemoApp');
const loadDemoCompact = () => import('../apps/demo/DemoApp');
const loadAccessControl = () => import('../apps/access-control/AccessControlApp');

export const generatedAppRegistry: readonly ShellAppDefinition[] = [
  {
    key: "demo",
    path: "/apps/demo",
    title: "Demo App · 通用",
    subtitle: "隨可用空間調整版面",
    description: "離線示範共用操作與資料狀態；內容依手機、平板與桌面的可用寬度排列。",
    icon: Monitor,
    status: "preview",
    displayMode: "responsive",
    load: loadDemo,
    access: "public",
  },
  {
    key: "demo-compact",
    path: "/apps/demo-compact",
    title: "Demo App · 窄版",
    subtitle: "大螢幕也保持窄版",
    description: "整個 App 視窗（含標題與外框）最大寬度 420 px 並置中；小螢幕依可用空間縮小。",
    icon: Smartphone,
    status: "preview",
    displayMode: "compact",
    load: loadDemoCompact,
    access: "public",
  },
  {
    key: "access-control",
    path: "/apps/access-control",
    title: "會員與權限",
    subtitle: "會員狀態、App 權限與安裝管理",
    description: "由平台管理員管理會員，以及各 App 對一般會員的開放方式。",
    icon: ShieldCheck,
    status: "preview",
    displayMode: "responsive",
    load: loadAccessControl,
    access: "identity",
  },
];
