// Generated by scripts/generate-app-registry.mjs. Do not edit directly.
import { ShieldCheck } from 'lucide-react';
import type { ShellAppDefinition } from './types';

const loadAccessControl = () => import('../apps/access-control/AccessControlApp');

export const generatedAppRegistry: readonly ShellAppDefinition[] = [
  {
    key: "access-control",
    path: "/apps/access-control",
    title: "會員與權限",
    subtitle: "會員狀態、App 權限與安裝管理",
    description: "由平台管理員管理會員，以及各 App 對一般會員的開放方式。",
    icon: ShieldCheck,
    status: "preview",
    displayMode: "responsive",
    load: loadAccessControl,
    access: "identity",
  },
];
