from __future__ import annotations

from typing import Protocol

from .models import AppGrant, AppInstallation, AppPolicy, IdentityPrincipal, Member, MemberPatch


class TokenVerifier(Protocol):
    def verify(self, token: str) -> IdentityPrincipal: ...


class ClaimsWriter(Protocol):
    def set_admin(self, uid: str, *, enabled: bool) -> None: ...


class MemberRepository(Protocol):
    def synchronize(self, principal: IdentityPrincipal, *, bootstrap_admin: bool) -> Member: ...

    def get(self, uid: str) -> Member | None: ...

    def list(self, *, limit: int = 100) -> list[Member]: ...

    def update(self, uid: str, patch: MemberPatch, *, actor_uid: str) -> Member: ...

    def set_app_grant(self, uid: str, grant: AppGrant, *, actor_uid: str) -> Member: ...

    def list_enabled_app_keys(self) -> list[str]: ...

    def list_app_policies(self) -> list[AppPolicy]: ...

    def set_app_policy(self, policy: AppPolicy, *, actor_uid: str) -> AppPolicy: ...

    def list_app_installations(self) -> list[AppInstallation]: ...

    def set_app_installation(self, installation: AppInstallation, *, actor_uid: str) -> AppInstallation: ...
